### ISSUE TITLE
Feature Request: Capture filters, projects in completed tasks

### ISSUE THREAD

**Issue by jadoff630** [Ledaryy/obsidian-todoist-completed-tasks#12]
If it isn't already possible (I could be missing it), it would be great to be able to get the project name and label for the completed tasks.

**Comment by Ledaryy** [comment]
Hi @jadoff630,

Thanks for using the plugin.

This feature is not yet developed. I think it is possible to extract this data from the Todoist API.
But I'm not sure how the description should be displayed, do you have any ideas/mock-ups?
For example:

* Buy groceries (Description here) [Label here]

Will that work for you?

**Comment by jadoff630** [comment]
I also use the todoist plugin (https://github.com/jamiebrynes7/obsidian-todoist-plugin) for in progress items and this is how they use labels and projects. 

![image](https://user-images.githubusercontent.com/25085973/194731329-03cc6de1-e725-45f0-9aa4-d404312219bb.png)

It could be interesting to have the completed tasks do this: 
- Task name (Description Here) Label, Project

It would be great if those fonticons for projects and labels that the other plugin uses could be placed there too. so it would look like:
- Task name (Description Here) [icon1] Label, [icon2] Project

**Comment by Ledaryy** [comment]
Thanks for the suggestions, I'll give it a try!
But I think it will not be possible to place the icons. As we render the tasks as raw text. The todoist plugin uses HTML for this. 
I think probably in the future we can introduce HTML too.

**Comment by jadoff630** [comment]
Awesome! Just the test is great :D

**Comment by blankster** [comment]
@Ledaryy I'd like to first express my gratitude for creating such an excellent plugin. I've been using it to document completed tasks in the daily note for each respective day. Your plugin meets 80% of what I hoped for.

However, as Peter mentioned, it would be extremely beneficial for me to be able to structure tasks by projects and subprojects. I utilize Todoist for several diverse areas of my life, and organizing tasks under the correct project or subproject helps keep task descriptions concise and provides context. Therefore, having this information available via a placeholder would be immensely helpful. The ideal version of this feature would include project and subproject headings, and for each project, a block consisting of individual tasks. Nevertheless, even just the placeholder would be a significant improvement, which I would likely use in the prefix or postfix.

I am more than willing to make a donation to support this, as I understand the many demands on one's attention in life, and I appreciate the value of this work. Extracting the required information should be feasible through the API request. The only remaining piece would be a placeholder that correctly combines the main project and subproject.

I find this plugin so important because otherwise you always struggle with what you still have to do, but forget how much I have actually done. Being aware of that helps me personally a lot and provides me with additional energy. That's why I find your plugin so useful.

**Comment by Ledaryy** [comment]
Hey @blankster @jadoff630,
I've developed it in a way that will render project names as headers. Please refer to the screenshot below:
![projects_headers](https://github.com/Ledaryy/obsidian-todoist-completed-tasks/assets/49571170/5f4366b4-b511-434f-888e-ce682c2b842c)
Maybe in the future, I'll refactor it to make it work the same as the Todoist sync plugin (as suggested by @jadoff630), but currently, it is out of scope.

Also, thanks for all the warm words and support! Don't feel obligated to sponsor, but any help is very appreciated!
