### ISSUE TITLE
Completed tasks can no longer be fetched

### ISSUE THREAD

**Issue by MorayM** [Ledaryy/obsidian-todoist-completed-tasks#41]
When fetching completed tasks through either "Fetch today's completed tasks" or "Fetch completed tasks using dates in segments", tasks are not fetched and the following error appears in the console:

<img width="951" alt="Screenshot 2024-01-11 at 11 19 54" src="https://github.com/Ledaryy/obsidian-todoist-completed-tasks/assets/15327509/b9e8aaaa-57ab-493d-9040-9cc1f6e6aa17">

I'm using Obsidian 1.5.3 and TCT plugin version 1.5.0

**Comment by Ledaryy** [comment]
Hi @MorayM ,

Same issue here, it seems like Todoist API returns an empty response
Like this:
{"items":[],"projects":{},"sections":{}}
Instead of actual tasks
I'm not sure if they changed the schema for fetching the completed task, or if it's just another bug on their side.

I'll try to reach out to them.

**Comment by MorayM** [comment]
Thanks. I figured something had changed at their end from the network inspector but I'm not familiar enough with their API or this codebase to figure out what!

**Comment by Ledaryy** [comment]
@MorayM It magically started working again on my side. Is everything good on yours?

**Comment by ricir** [comment]
For me too it is working now!

**Comment by MorayM** [comment]
@Ledaryy it's working for me too, guess someone at Todoist pushed the wrong thing to production!
